version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./srv/nginx:/etc/nginx/conf.d
  ldap:
    image: osixia/openldap:1.5.0
    volumes:
        - "ldapdb:/var/lib/ldap"
        - "ldapconfig:/etc/ldap/slapd.d"
    environment:
        - "LDAP_ORGANISATION=Eco du Boiron"
        - "LDAP_DOMAIN=ecoduboiron.ch"
        - "LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}"
        - "LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}"
    restart: always

  ldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
       - PHPLDAPADMIN_LDAP_HOSTS=ldap
    restart: always

volumes:
  ldapdb:
  ldapconfig:

