version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./srv/nginx:/etc/nginx/conf.d
      - ./srv/certbot/conf:/etc/letsencrypt
      - ./srv/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:arm32v6-latest
    volumes:
      - ./srv/certbot/conf:/etc/letsencrypt
      - ./srv/certbot/www:/var/www/certbot
      - ./srv/certbot/log:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  ldap:
    image: osixia/openldap:1.5.0
    volumes:
        - "ldapdb:/var/lib/ldap"
        - "ldapconfig:/etc/ldap/slapd.d"
    restart: always
  ldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
       - PHPLDAPADMIN_LDAP_HOSTS=ldap
    restart: always

volumes:
  ldapdb:
  ldapconfig:
  backup:
    driver: local
    driver_opts:
      type: ext4
      device: /dev/disk/by-label/backup

